Create PostmanCollection.md
TiendaNube/api-docs pull request #112
Opened 2021-02-26 20:24 UTC by Nahpal

Ainda temos que finalizar

2021-03-01 18:12 UTC, gustavocgatto commented
@lombo criamos a documentação com a Postman Collection que temos para que possa ser utilizada pelos parceiros. Isso vai ajudá-los muito no desenvolvimento. Por gentileza, você poderia verificar se está tudo certo? Muito obrigado!

2021-03-01 20:07 UTC, lombo commented
Could we please:
1. Move these files to a `utils/postman/` folder
2. Rename `PostmanCollection.md` to `README.md`
3. Delete `teste.md`

2021-03-01 20:08 UTC, lombo requested changes
Could we please:
1. Move these files from `utils` to `utils/postman/` folder.
2. Rename `PostmanCollection.md` to `README.md`.
3. Delete `teste.md`.

2021-03-02 13:02 UTC, Nahpal commented
Thanks @lombo for the feedback.

We updated those points.

Could you check it again please?

2021-03-08 18:28 UTC, Nahpal commented
Gatto added authorization endpoint in the last commit

2021-03-08 21:34 UTC, lombo approved these changes
🚢

2021-03-09 12:26 UTC, merged