Update postman collection with Abandoned Checkout
TiendaNube/api-docs pull request #144
Opened 2021-05-19 16:59 UTC by ferrari-lucas

## [1.3.0] - 2021-05-19
  
Abandoned Checkout API methods included according to the documentation available at https://github.com/TiendaNube/api-docs/blob/master/resources/abandoned_checkout.md

### Added
- Folder Abandoned Checkout
  POST Create a discount coupon to the abandoned cart
  GET Receive all abandoned carts
  GET Receive a specific abandoned cart

2021-05-20 20:07 UTC, Nahpal requested changes
Delete access_token and use variable.

All the rest i think is fine

2021-05-20 20:07 UTC, Nahpal commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Change access_token for {{app_token}}

2021-05-20 20:07 UTC, Nahpal commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Change access_token for {{app_token}}

2021-05-20 20:07 UTC, Nahpal commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Change access_token for {{app_token}}

2021-05-20 21:55 UTC, ferrari-lucas commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Resolved [here](https://github.com/TiendaNube/api-docs/pull/144/commits/23b482ce6188891bb22c18de4ee4214b21bbf69c)

2021-05-20 21:55 UTC, ferrari-lucas commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Resolved [here](https://github.com/TiendaNube/api-docs/pull/144/commits/23b482ce6188891bb22c18de4ee4214b21bbf69c)

2021-05-20 21:55 UTC, ferrari-lucas commented on utils/postman/postman.json
> +								"value": "bearer cba3bc57074e24c0b713fd774973ffd28a2d25c3",
Resolved [here](https://github.com/TiendaNube/api-docs/pull/144/commits/23b482ce6188891bb22c18de4ee4214b21bbf69c)

2021-05-24 12:11 UTC, Nahpal approved these changes
Awesome!

2021-05-24 14:26 UTC, merged