Including documentation for Abandoned checkout API
TiendaNube/api-docs pull request #145
Opened 2021-05-19 17:21 UTC by ferrari-lucas

2021-05-19 17:54 UTC, gustavocgatto approved these changes
Perfect!

2021-05-20 20:17 UTC, Nahpal requested changes
Awesome work!

Just 2 small wordings to change i think

2021-05-20 20:17 UTC, Nahpal commented on resources/abandoned_checkout.md
> +The abandoned checkout is created when the customer reaches the second checkout step with the cart, but for some reason it does not finish the process.
Change for:

"The abandoned checkout is created when the customer reaches checkout's seconds step, but for some reason it does not finish the process."

2021-05-20 20:17 UTC, Nahpal commented on resources/abandoned_checkout.md
> +> ***Note:*** A purchase is only converted into a cart if the customer has arrived for the second checkout step.
Change for:

"A purchase is only converted into an abandoned cart if the customer has arrived to checkout's second step."

2021-05-20 21:59 UTC, ferrari-lucas commented on resources/abandoned_checkout.md
> +The abandoned checkout is created when the customer reaches the second checkout step with the cart, but for some reason it does not finish the process.
Resolved [here](https://github.com/TiendaNube/api-docs/pull/145/commits/33e228baa64813eb883514277cb3eae09cfeeeff)

2021-05-20 21:59 UTC, ferrari-lucas commented on resources/abandoned_checkout.md
> +> ***Note:*** A purchase is only converted into a cart if the customer has arrived for the second checkout step.
Resolved [here](https://github.com/TiendaNube/api-docs/pull/145/commits/33e228baa64813eb883514277cb3eae09cfeeeff)

2021-05-22 01:11 UTC, heyBett commented
Boa noite pessoal! Temos previsão para um webhook de abandoned_checkout? Os clientes pedem muito para recuperação de carrinho no meu app da RD Station.

2021-05-24 12:13 UTC, Nahpal approved these changes
Great!

2021-05-24 14:24 UTC, merged