Added the customs object to the shipping Address
TiendaNube/api-docs pull request #146
Opened 2021-05-19 21:04 UTC by Raykardaguiar

neste commit estamos adicionando um campo custom dentro do objeto shipping_address, este campo tem a finalidade de qualquer campo adicional que seja necessário adicionar no objeto.

2021-05-20 20:24 UTC, evertondepaula reviewed
@Raykardaguiar temos um arquivo adicionado guides/Shipping Provider/images/Gestão de envíos-Gestão de envios.png, o que seria ele?

2021-05-20 20:24 UTC, evertondepaula commented on resources/order.md
> +| customs                    | An object to insert additional information into the shipping address |
@Raykardaguiar realmente não colocaria essa property aqui, fica parecendo que o modelo de order possui um `customs` e não que shipping_address possuí customs.

2021-05-20 20:24 UTC, evertondepaula commented on resources/order.md
> +| custom      | The shipping_address custom fields. The default is null                                     | Object | No       |
Podemos dar um exemplo de como seria um customs fields, podemos usar os dados de México por exemplo.

2021-05-21 14:33 UTC, Raykardaguiar commented on resources/order.md
> +| custom      | The shipping_address custom fields. The default is null                                     | Object | No       |
Inseri um exemplo no get de orders.

2021-05-26 18:52 UTC, evertondepaula requested changes
@Raykardaguiar 
O que seria essa imagem?
`guides/Shipping Provider/images/Gestão de envíos-Gestão de envios.png`.

2021-05-26 18:55 UTC, Raykardaguiar commented
> @Raykardaguiar
> O que seria essa imagem?
> `guides/Shipping Provider/images/Gestão de envíos-Gestão de envios.png`.

@evertondepaula Essa imagem está vindo da master e já se encontra no projeto no mesmo path, sempre que descarto ele vem pra commitar novamente. Suspeitamos que quem subiu a estava utilizando o windows e está dando algum conflito de versão com o MacOs.

2021-05-27 14:45 UTC, closed without merging