Update Doc Fulfillment
TiendaNube/api-docs pull request #154
Opened 2021-06-28 17:40 UTC by bcfnuvem

# Description
New date validate API change fulfillment doc api.

# Tech Design document
https://docs.google.com/document/d/1sJ8ItXaWHEftxjBeRBrATwxGWr_qD_mk3axlAOSRkhs/edit?ts=60d616b7#

# Related PR's
https://github.com/TiendaNube/tiendanube/pull/15981

2021-06-28 21:21 UTC, car7axo requested changes

2021-06-28 21:21 UTC, car7axo commented on resources/shipping_carrier.md
> +   "happened_at": "2021-01-32",
O que acha de colocar um exemplo mais comum que é o envio da data no formato errado ?
```suggestion
   "happened_at": "28-01-2021",
```
[Referência](https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/)

2021-06-29 12:50 UTC, evertondepaula requested changes

2021-06-29 12:50 UTC, evertondepaula commented on resources/shipping_carrier.md
> +Valid dates ISO-8601 are:
@bcfnuvem 
Podemos também deixar exemplos de datas inválidas?

2021-06-30 14:11 UTC, gilbertojb approved these changes

2021-06-30 14:19 UTC, gilbertojb commented on resources/shipping_carrier.md
> +| 2021-03-03                 | YYYY-MM-DD                                                     |
@bcfnuvem todos esses patterns estão sendo validados na implementação?

Não encontrei a validação desses patterns nos testes. Seria bom tê-los também.
`YYYY-MM-DD hh:mm:ss±hhmm` / `YYYY-MM-DD hh:mmZ` / `YYYY-MM-DDThh:mmZ`

2021-06-30 15:34 UTC, bcfnuvem commented on resources/shipping_carrier.md
> +| 2021-03-03                 | YYYY-MM-DD                                                     |
Os testes foram adicionados no cenários de testes do core.

2021-06-30 16:36 UTC, evertondepaula approved these changes

2021-07-06 13:32 UTC, merged