Draft Order API
TiendaNube/api-docs pull request #92
Opened 2020-10-01 19:32 UTC by lucasmariani17

Documentation for the draft order API. [Create a draft order]

2020-11-24 23:55 UTC, tatilattanzi requested changes
actualizamos el readme también?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +A draft order is created when the merchant manages a pre-sale made outside the platform. Draft orders also can be created through the API.
@lucasmariani17 está muy especifico en un unico caso de uso, todavía tenemos más... podríamos brindar más color de qué una draft order "permite"? ejemplo:

`A draft order enables create orders through outside channels (...)`

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +>[Get a draft order collection](#GET-draft-orders)
list all draft orders, no?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| storefront                 | Name that refers to the means by which the draft order was managed.                                      |
no es el "Origin of the order"? y podríamos dar ejemplos de contenido?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| hash                       | Specifies the location of the Draft Order.                                                               |
eso no viene en el payload 🤔

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| lang                       | Draft Order's language used by the customer during the checkout process.                                 |
2 comments acá:
- en el payload esta `language`
- hace falta la aclaración "checkout process"? porque no necesariamente va pasar por el checkout, verdad?

```suggestion
| language                       | Draft Order's language used by the customer during the checkout process.                                 |
```
```suggestion
| lang                       | Draft Order's language used by the customer during the checkout process.                                 |
```lan

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| cpf_cnpj                   | Customer identity number.                                                                                |
acá tengo dudas: son los parametros para la creación de una draft orders o propriedades de una draft order (el body del response?) porque la verdad es que son diferentes, en ese caso nos conviene separar para cada ruta 🙏

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| shipping_option            | The shipping option chosen by the customer during the checkout process.                                  |
+1 para el comment de "checkout process"

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| owner_note                 | Store owner's note about the draft order.                                                                |
no deberia ser "Merchant owner's note (...)"?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| shipping_pickup_type       | "ship" if the order is going to be shipped; "pickup" if it's going to be picked up from a store branch.  |
en realidad el pickup no necesariamente es en una store branch (podria ser una sucursal o otro local)

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| initiated_by               | Unique identifier number that indicates the user who started the Draft Order.                            |
el `initiated_by` parte deberiamos poner nosotros, no?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| checkout_url               | Url of the checkout corresponding to the draft order.                                                    |
+1 esa parte generamos nosotros, no?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| created_at                 | Date when the Draft Order was last updated in [ISO 8601 format](http://es.wikipedia.org/wiki/ISO_8601).  |
+1 esa parte generamos nosotros, no?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +Get a draft order collection.
`List all (...)`

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +         "coupon":[],
podriamos poner dados más realistas? id `1`, `null` y `0.00` no son tan representativos... para los campos que sí pueden ser null aclaramos en la definición del campo (sea para el GET o POST)

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +         "shipping_pickup_type":"ship",
+1 dados realistas / representativos

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +         "created_at":"-0001-11-30T00:00:00+0000",
+1, y en ese caso no poner un formato invalido 🙏

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +            "date":"-0001-11-30 00:00:00.000000",
+1 invalido

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +                  "src":"https://d26lpennugtm8s.cloudfront.net/stores/001/330/104/products/my-first-product.jpg",
acá podriamos poner algo como "www.example.com/cualquier-cosa", no necesita ser tan realista así (por seguridad)

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +               ],
qué significa ese array?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +         "checkout_url":"https://mystore.mitiendanube.com/checkout/v3/start/325505360/234ae927c2248a18e9ae3b5a6e9a19e38ae26e96?from_store=1"
+1 no hace falta taaan realista

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +      "results":[
podriamos aclarar esa parte en la doc tmb, no?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +            "shipping_max_days":null,
en el paginator tenemos el mismo body que arriba? 🤔

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +   "shipping_min_days":null,
+1 mismos comments para los datos

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +| sale_channel       | Sales channel name.                                                                             |  string  | No       |
podriamos brindar un ejemplo?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +   "shipping_option": "Te vamos a contactar para coordinar la entrega!",
inglés

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +   "checkout_url": "https://mystore.mitiendanube.com/checkout/v3/order/proxy/39138177/945f71f08398e25a7ae6fcf961e9cc10417278c8",
+1

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +#### POST /draft-orders/1/confirm
el id podria ser más representativo que 1

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +    "abandoned_checkout_url": "https://mystore.mitiendanube.com/checkout/v3/order/proxy/325520041/dcf448d80994fb50712785ac433fc06ebe78092b",
+1 no taan representativo

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +    "billing_province": null,
+1 más representativos

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +            }
con 1 direción estamos, no? no hace falta tantas

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +            "name": "Oleo Esencial Barba 30Ml",
inglés

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +            "height": "0.00",
más representativo

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +#### DELETE /draft-orders/1
+1 id más representativo

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +`HTTP/1.1 200 OK`
podria tener otros status además del `200`? podriamos aclarar acá?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +#### GET /draft-orders/1
id más representativo

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +`HTTP/1.1 200 OK`
podria tener más status además del `200`, no? aclaramos acá el `404`y `5xx`?

2020-11-24 23:55 UTC, tatilattanzi commented on resources/draft_order.md
> +`HTTP/1.1 200 OK`
es `201`, no?

y aclarar los otros status que podriamos tener (bad request, internal server error)

2020-11-26 18:27 UTC, lucasmariani17 commented on resources/draft_order.md
> +A draft order is created when the merchant manages a pre-sale made outside the platform. Draft orders also can be created through the API.
@tatilattanzi decis de reemplazar lo que esta o sumarle la información que mencionas?

2020-11-26 19:06 UTC, lucasmariani17 commented on resources/draft_order.md
> +`HTTP/1.1 200 OK`
Aca no sería un 200? Dado que en realidad no se crea una nueva draft, si no que se hace el update del status a pagada pasando a ser una orden. 🤔

2020-11-30 12:14 UTC, tatilattanzi commented on resources/draft_order.md
> +| promotional_discount       | Promotional discount applied to the draft order.
acá podriamos tener el link para el `promotional_discount`: `[Promotional Discount](#PromotionalDiscount)`

2020-11-30 12:14 UTC, tatilattanzi commented on resources/draft_order.md
> +| products                   | List of the products purchased by the `customer`. Contents are explained below and values hold are the ones corresponding to the time the products were purchased.
+1 link para `products`

2020-11-30 17:02 UTC, tatilattanzi approved these changes

2020-12-03 11:07 UTC, merged